### ISSUE TITLE
Required file downloaded.txt does not exist

### ISSUE THREAD

**Issue by yol** [endofhome/patreon-downloader#1]
JS tries to read `persistence/downloaded.txt`: https://github.com/endofhome/patreon-downloader/blob/master/js/files.js#L6

After checkout this files does not exist.

**Comment by endofhome** [comment]
Thanks for raising this issue (and a few others). Apologies for the delay in taking a look - I'll hope to deal with all of these shortly.

I think the missing file is OK, but the script should handle this case.
I hope this has been fixed now - https://github.com/endofhome/patreon-downloader/commit/3738461bfcc0abd6683783d8b458eb8005a5f284
