### ISSUE TITLE
cURL call does not follow redirects

### ISSUE THREAD

**Issue by yol** [endofhome/patreon-downloader#3]
curl call here: https://github.com/endofhome/patreon-downloader/blob/master/bin/download-mp3.sh#L17 should have `-L` set because patreon usually answers with a redirect to the CDN

**Comment by endofhome** [comment]
I haven't run into this issue at all - but I don't see the harm in updating the cURL call.

Should be fixed in https://github.com/endofhome/patreon-downloader/commit/553b77d7ddaa325837aa32304a870b4406811421
I also added -L to the artwork download for good luck.
